export const homeObjOne = {
  id: "about",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "",
  headline: "Bla Software is ...",
  description: "Since our inception in 2008, Bla Software is the wisdom, .....",
  line: "",
  buttonLabel: "Contact Us",
  imgStart: false,
  img: "images/svg6.svg",
  alt: "Car",
  dark: true,
  primary: true,
  darkText: true,
};
export const homeObjTwo = {
  id: "product",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "PRODUCT DEVELOPMENT & DESIGN",
  headline: "",
  description: "",
  line: "We are experts in mobile application, web design, game programming. The development .......",
  buttonLabel: "Learn More ",
  imgStart: true,
  img: "images/svg5.svg",
  alt: "Piggybank",
  dark: false,
  primary: false,
  darkText: true,
};
